//user
export const GET_REGISTER_REQUEST = "GET_REGISTER_REQUEST";
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS";
export const GET_REGISTER_ERROR = "GET_REGISTER_ERROR";

export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR";

export const GET_USER_DATA_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";

export const USER_PASSWORD_REQUEST = "USER_PASSWORD_REQUEST";
export const USER_PASSWORD_SUCCESS = "USER_PASSWORD_SUCCESS";
export const USER_PASSWORD_ERROR = "USER_PASSWORD_ERROR";

export const USER_DATA_REQUEST = "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_ERROR = "USER_DATA_ERROR";

export const USER_FORGET_PASSWORD_REQUEST = "USER_FORGET_PASSWORD_REQUEST";
export const USER_FORGET_PASSWORD_SUCCESS = "USER_FORGET_PASSWORD_SUCCESS";
export const USER_FORGET_PASSWORD_ERROR = "USER_FORGET_PASSWORD_ERROR";

//Gernal 
export const CLOSE_SUCCESS_MODAL = "CLOSE_SUCCESS_MODAL";

//Events

export const GET_EVENT_REQUEST="GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS="GET_EVENT_SUCCESS";
export const GET_EVENT_ERROR="GET_EVENT_ERROR";

//EventsById

export const GET_EVENTBYID_REQUEST = "GET_EVENTBYID_REQUEST";
export const GET_EVENTBYID_SUCCESS = "GET_EVENTBYID_SUCCESS";
export const GET_EVENTBYID_ERROR = "GET_EVENTBYID_ERROR";
//category

export const GET_CATEGORY_REQUEST="GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR="GET_CATEGORY_ERROR"

//state&city

export const GET_STATEANDCITY_REQUEST="GET_STATEANDCITY_REQUEST";
export const GET_STATEANDCITY_SUCCESS="GET_STATEANDCITY_SUCCESS";
export const GET_STATEANDCITY_ERROR="GET_STATEANDCITY_ERROR";

//state&cityevent

export const GET_STATEANDCITYEVENT_REQUEST="GET_STATEANDCITYEVENT_REQUEST";
export const GET_STATEANDCITYEVENT_SUCCESS="GET_STATEANDCITYEVENT_SUCCESS";
export const GET_STATEANDCITYEVENT_ERROR="GET_STATEANDCITYEVENT_ERROR";

//addcomment

export const POST_ADDCOMMENT_REQUEST="POST_ADDCOMMENT_REQUEST";
export const POST_ADDCOMMENT_SUCCESS="POST_ADDCOMMENT_SUCCESS";
export const POST_ADDCOMMENT_ERROR="POST_ADDCOMMENT_ERROR";

//getEventDescription

export const GET_EVENTDESCRIPTION_REQUEST="GET_EVENTDESCRIPTION_REQUEST";
export const GET_EVENTDESCRIPTION_SUCCESS="GET_EVENTDESCRIPTION_SUCCESS";
export const GET_EVENTDESCRIPTION_ERROR="GET_EVENTDESCRIPTION_ERROR";

// forlikeevent

export const POST_EVENT_LIKE_REQUEST="POST_EVENT_LIKE_REQUEST";
export const POST_EVENT_LIKE_SUCCESS="POST_EVENT_LIKE_SUCCESS";
export const POST_EVENT_LIKE_ERROR="POST_EVENT_LIKE_ERROR";

// for interested event

export const GET_INTERSTEDEVENT_REQUEST="GET_INTERSTEDEVENT_REQUEST";
export const GET_INTERSTEDEVENT_SUCCESS="GET_INTERSTEDEVENT_SUCCESS";
export const GET_INTERSTEDEVENT_ERROR="GET_INTERSTEDEVENT_ERROR";

//For Attending events

export const GET_ATTENDING_EVENT_REQUEST="GET_ATTENDING_EVENT_REQUEST";
export const GET_ATTENDING_EVENT_SUCCESS="GET_ATTENDING_EVENT_SUCCESS";
export const GET_ATTENDING_EVENT_ERROR="GET_ATTENDING_EVENT_ERROR";

//For Join Events

export const POST_JOINING_EVENTS_REQUEST = "POST_JOINING_EVENTS_REQUEST";
export const POST_JOINING_EVENTS_SUCCESS = "POST_JOINING_EVENTS_SUCCESS";
export const POST_JOINING_EVENTS_ERROR = "POST_JOINING_EVENTS_ERROR";