export const GET_REGISTER_REQUEST = "GET_REGISTER_REQUEST";
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS";
export const GET_REGISTER_ERROR = "GET_REGISTER_ERROR";

//Gernal 
export const OPEN_INVEST_MODAL = "OPEN_INVEST_MODAL";

//Events

export const GET_EVENT_REQUEST="GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS="GET_EVENT_SUCCESS";
export const GET_EVENT_ERROR="GET_EVENT_ERROR";

//category

export const GET_CATEGORY_REQUEST="GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR="GET_CATEGORY_ERROR"

//state&city

export const GET_STATEANDCITY_REQUEST="GET_STATEANDCITY_REQUEST";
export const GET_STATEANDCITY_SUCCESS="GET_STATEANDCITY_SUCCESS";
export const GET_STATEANDCITY_ERROR="GET_STATEANDCITY_ERROR";

//state&cityevent

export const GET_STATEANDCITYEVENT_REQUEST="GET_STATEANDCITYEVENT_REQUEST";
export const GET_STATEANDCITYEVENT_SUCCESS="GET_STATEANDCITYEVENT_SUCCESS";
export const GET_STATEANDCITYEVENT_ERROR="GET_STATEANDCITYEVENT_ERROR";

//addcomment

export const POST_ADDCOMMENT_REQUEST="POST_ADDCOMMENT_REQUEST";
export const POST_ADDCOMMENT_SUCCESS="POST_ADDCOMMENT_SUCCESS";
export const POST_ADDCOMMENT_ERROR="POST_ADDCOMMENT_ERROR";