//user
export const GET_REGISTER_REQUEST = "GET_REGISTER_REQUEST";
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS";
export const GET_REGISTER_ERROR = "GET_REGISTER_ERROR";

export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR";

export const GET_SOCIAL_LOGIN_REQUEST = "GET_SOCIAL_LOGIN_REQUEST";
export const GET_SOCIAL_LOGIN_SUCCESS = "GET_SOCIAL_LOGIN_SUCCESS";
export const GET_SOCIAL_LOGIN_ERROR = "GET_SOCIAL_LOGIN_ERROR";

export const GET_USER_DATA_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";

export const USER_PASSWORD_REQUEST = "USER_PASSWORD_REQUEST";
export const USER_PASSWORD_SUCCESS = "USER_PASSWORD_SUCCESS";
export const USER_PASSWORD_ERROR = "USER_PASSWORD_ERROR";

export const USER_DATA_REQUEST = "USER_DATA_REQUEST";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_ERROR = "USER_DATA_ERROR";

export const UPDATE_USER_DATA_REQUEST = "UPDATE_USER_DATA_REQUEST";
export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_ERROR = "UPDATE_USER_DATA_ERROR";

export const USER_FORGET_PASSWORD_REQUEST = "USER_FORGET_PASSWORD_REQUEST";
export const USER_FORGET_PASSWORD_SUCCESS = "USER_FORGET_PASSWORD_SUCCESS";
export const USER_FORGET_PASSWORD_ERROR = "USER_FORGET_PASSWORD_ERROR";

//Gerenal 
export const CLOSE_SUCCESS_MODAL = "CLOSE_SUCCESS_MODAL";
export const CLEAN_COMMENT_SUCCESS = "CLEAN_COMMENT_SUCCESS";

//get Interest
export const GET_INTEREST_REQUEST = "GET_INTEREST_REQUEST";
export const GET_INTEREST_SUCCESS = "GET_INTEREST_SUCCESS";
export const GET_INTEREST_ERROR = "GET_INTEREST_ERROR";

//device token
export const STORE_TOKEN_REQUEST = "STORE_TOKEN_REQUEST";
export const STORE_TOKEN_SUCCESS = "STORE_TOKEN_SUCCESS";
export const STORE_TOKEN_ERROR = "STORE_TOKEN_ERROR";

//Events

export const GET_EVENT_REQUEST="GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS="GET_EVENT_SUCCESS";
export const GET_EVENT_ERROR="GET_EVENT_ERROR";

export const GET_LIKEEVENT_REQUEST="GET_LIKEEVENT_REQUEST";
export const GET_LIKEEVENT_SUCCESS="GET_LIKEEVENT_SUCCESS";
export const GET_LIKEEVENT_ERROR="GET_LIKEEVENT_ERROR";

export const GET_TODAY_EVENT_REQUEST="GET_TODAY_EVENT_REQUEST";
export const GET_TODAY_EVENT_SUCCESS="GET_TODAY_EVENT_SUCCESS";
export const GET_TODAY_EVENT_ERROR="GET_TODAY_EVENT_ERROR";

//EventsById

export const GET_EVENTBYID_REQUEST = "GET_EVENTBYID_REQUEST";
export const GET_EVENTBYID_SUCCESS = "GET_EVENTBYID_SUCCESS";
export const GET_EVENTBYID_ERROR = "GET_EVENTBYID_ERROR";
//category

export const GET_CATEGORY_REQUEST="GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS="GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR="GET_CATEGORY_ERROR"

//state&city

export const GET_STATEANDCITY_REQUEST="GET_STATEANDCITY_REQUEST";
export const GET_STATEANDCITY_SUCCESS="GET_STATEANDCITY_SUCCESS";
export const GET_STATEANDCITY_ERROR="GET_STATEANDCITY_ERROR";

//state&cityevent

export const GET_STATEANDCITYEVENT_REQUEST="GET_STATEANDCITYEVENT_REQUEST";
export const GET_STATEANDCITYEVENT_SUCCESS="GET_STATEANDCITYEVENT_SUCCESS";
export const GET_STATEANDCITYEVENT_ERROR="GET_STATEANDCITYEVENT_ERROR";

//addcomment

export const POST_ADDCOMMENT_REQUEST="POST_ADDCOMMENT_REQUEST";
export const POST_ADDCOMMENT_SUCCESS="POST_ADDCOMMENT_SUCCESS";
export const POST_ADDCOMMENT_ERROR="POST_ADDCOMMENT_ERROR";

//like comment
export const POST_LIKECOMMENT_REQUEST="POST_LIKECOMMENT_REQUEST";
export const POST_LIKECOMMENT_SUCCESS="POST_LIKECOMMENT_SUCCESS";
export const POST_LIKECOMMENT_ERROR="POST_LIKECOMMENT_ERROR";

//getEventDescription

export const GET_EVENTDESCRIPTION_REQUEST="GET_EVENTDESCRIPTION_REQUEST";
export const GET_EVENTDESCRIPTION_SUCCESS="GET_EVENTDESCRIPTION_SUCCESS";
export const GET_EVENTDESCRIPTION_ERROR="GET_EVENTDESCRIPTION_ERROR";

// forlikeevent

export const POST_EVENT_LIKE_REQUEST="POST_EVENT_LIKE_REQUEST";
export const POST_EVENT_LIKE_SUCCESS="POST_EVENT_LIKE_SUCCESS";
export const POST_EVENT_LIKE_ERROR="POST_EVENT_LIKE_ERROR";

// for interested event

export const GET_INTERSTEDEVENT_REQUEST="GET_INTERSTEDEVENT_REQUEST";
export const GET_INTERSTEDEVENT_SUCCESS="GET_INTERSTEDEVENT_SUCCESS";
export const GET_INTERSTEDEVENT_ERROR="GET_INTERSTEDEVENT_ERROR";

//For Attending events

export const GET_ATTENDING_EVENT_REQUEST="GET_ATTENDING_EVENT_REQUEST";
export const GET_ATTENDING_EVENT_SUCCESS="GET_ATTENDING_EVENT_SUCCESS";
export const GET_ATTENDING_EVENT_ERROR="GET_ATTENDING_EVENT_ERROR";

// Notification Api
export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST'; 
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS'; 
export const GET_NOTIFICATION_ERROR = 'GET_NOTIFICATION_ERROR'; 

//For Join Events

export const POST_JOINING_EVENTS_REQUEST = "POST_JOINING_EVENTS_REQUEST";
export const POST_JOINING_EVENTS_SUCCESS = "POST_JOINING_EVENTS_SUCCESS";
export const POST_JOINING_EVENTS_ERROR = "POST_JOINING_EVENTS_ERROR";

export const SET_ADD_EVENT_DEFAULT = "SET_ADD_EVENT_DEFAULT";

export const SET_LIKE_EVENTS_DEFAULT = "SET_LIKE_EVENTS_DEFAULT";

export const SET_SELECTED_EVENT = "SET_SELECTED_EVENT";

// constanst for weekly events
export const GET_WEEKLY_EVENTS_REQUEST = "GET_WEEKLY_EVENTS_REQUEST";
export const GET_WEEKLY_EVENTS_SUCCESS = "GET_WEEKLY_EVENTS_SUCCESS";
export const GET_WEEKLY_EVENTS_ERROR= "GET_WEEKLY_EVENTS_ERROR";

// constanst for past events
export const GET_PAST_EVENTS_REQUEST = "GET_PAST_EVENTS_REQUEST";
export const GET_PAST_EVENTS_SUCCESS = "GET_PAST_EVENTS_SUCCESS";
export const GET_PAST_EVENTS_ERROR= "GET_PAST_EVENTS_ERROR";

